### ISSUE TITLE
Port Not64 CPU Deviders option to wii64

### ISSUE THREAD

**Issue by carnage702** [emukidid/Wii64#17]
lots of games even with vwii overclock dont get full speed becuase the emulator is not using the new clock speed on their math, on not64 it works like night and day, putting cpu clock devider set to 1 and vwii overclock you basicaly get full speed is almost all games even hard games like conker and banjo.

So please port this option to make a great wii64 get manny games in full speed with no sloowdowns on rice and glide.

**Comment by emukidid** [comment]
This is done now.

**Comment by carnage702** [comment]
when can we expect a new release option here on github? for those of us that cant compile?

**Comment by emukidid** [comment]
I'm hoping soonish, just need to fix a few other issues and track down a crash that's occurring with the latest toolchain and the LTO flag enabled.

**Comment by carnage702** [comment]
Any chance rice mode ever gets FB textures implemented as well?

**Comment by carnage702** [comment]
So any chance of a compile with clock dividers for christmas? i wanted overclock ready to play with my causins xD
