### ISSUE TITLE
latest commits made 2d objects that were infront of 3d ones invisible

### ISSUE THREAD

**Issue by carnage702** [emukidid/Wii64#2]
in games like duke nukem 64 with rice and earthworm jim 3d the early rice commits showed the 2d objects even if they were infront of 3d ones, but the latest commit just makes all 2d objects from duke nukem 64 and earthworm jim 3 d collectibles invisible.

also earlier rice revs ingame both vigilante 8 games were almost perfect but now they just show no car models ingame.

**Comment by emukidid** [comment]
Can you specify which "early Rice commits"?

**Comment by carnage702** [comment]
i tryed bascicaly the first one fix94 builded day 14 im guessing before every not64 dynarec stuff.

vigilante 8 games had glitchy main menus but ingame they showed the car models and weapons and such only the hud flashed abit but it was perfectly playable.

duke dukem 64 all amno weapons and enemys showed up even though they showed up infront of 3d objects all the time.

earthworm jim collectibles marbles showed up again infront of the boxes that contained them but they did showed up.

im not sure which commit fix94 gave to me but its this dol
http://www.mediafire.com/file/am92y09ubvf5lyd/wii64_Rice.7z

**Comment by carnage702** [comment]
Also could you port not64 cpu cycle option aswhell? some games dont care if your wiiu is overclocking wii64 or not for isntance toy story 2 as an example, most games will only use the overclocked vwii speed if the cpu cycle is set to 1 on not64 and vwii is overclocked wich makes some games run perfectly smooth and much better than overclock without cpu cycles set to one.

**Comment by emukidid** [comment]
@FIX94 says it was an issue caused by a change he's made in his build

**Comment by carnage702** [comment]
i see what about adding the not64 cpu cycles for overclokced vwii then?

**Comment by emukidid** [comment]
Yeah, once the CPU clock detection stuff is in libOGC I will (which I'll probably need to make a pull request for).
