### ISSUE TITLE
Compiled version of wii64 with cpu clock divider option?

### ISSUE THREAD

**Issue by carnage702** [emukidid/Wii64#28]
Is there anyone who could compile the latest commits into a dol? tryed compilling wii64 but i couldnt.

**Comment by thunder-hammer** [comment]
Yeah there were a few hicups but I think I have it compiled. cloned master today and didn't change anything in the code so it should be what's on the master branch

[wii64-glN64.dol.zip](https://github.com/emukidid/Wii64/files/5289135/wii64-glN64.dol.zip)

I didn't really test it out yet beyond loading it in dolphin hope it works though.

**Comment by carnage702** [comment]
> 
> 
> Yeah there were a few hicups but I think I have it compiled. cloned master today and didn't change anything in the code so it should be what's on the master branch
> 
> [wii64-glN64.dol.zip](https://github.com/emukidid/Wii64/files/5289135/wii64-glN64.dol.zip)
> 
> I didn't really test it out yet beyond loading it in dolphin hope it works though. (any issues are likely because i'm new at compiling for wii)
> 
> Also it's awesome to see there are still commits going on this repo. Thanks to the developers.

while it does work its unusable

1- there is always giberishi writen on the screen , huge lines  saying frames/ fog numbers and memory available, im guessing you forgot to desable the debug stuff to always show on screen.
2-there is no speed limits now, all games speed go rampant, which means games play at 1.5 speed or 1.2 or whatever speed then can using the clock speed which means they all play too fast.
3- somehow wiiu gamepad support was disabled , so im guessing you missed a library somewhere.

**Comment by emukidid** [comment]
Where's 2 happening, in WiiVC mode? I'll take a look at compiling a release if I find some free time this week.

**Comment by carnage702** [comment]
> 
> 
> Where's 2 happening, in WiiVC mode? I'll take a look at compiling a release if I find some free time this week.

yes i have the wii64 wii vc inject and the latest release does work perfectly with wiiu gamepad this one compiled just doesnt see it at all.

also any chance to add not64 options like pitch scale(useful to not hear beep while loading save states) and maybe choose speed limit between dl/VI?

**Comment by thunder-hammer** [comment]
Thanks for the feedback.
 1. Yeah oops it is a debug build
 2. @emukidid I just ran this on my Wii and it seemed okay. So it looks like it is just a vwii issue.
 3. Not sure what I did wrong there... probably something like that.

Also this is an awesome improvement graphically over the previous build I was using (before the not64 merge I believe)

**Comment by carnage702** [comment]
> 
> 
> Where's 2 happening, in WiiVC mode? I'll take a look at compiling a release if I find some free time this week.

so any chance for that complile? it would be amazing with not64 fixes+ rice with cpu clock divider and all xD

**Comment by carnage702** [comment]
> 
> 
> Thanks for the feedback.
> 
>     1. Yeah oops it is a debug build
> 
>     2. @emukidid I just ran this on my Wii and it seemed okay. So it looks like it is just a vwii issue.
> 
>     3. Not sure what I did wrong there... probably something like that.
> 
> 
> Also this is an awesome improvement graphically over the previous build I was using (before the not64 merge I believe)

just wondering does the polygon gfx glitch and such also affec the rice build? can you compile a rice build with latest changes instead of just gl?

**Comment by thunder-hammer** [comment]
`can you compile a rice build with latest changes instead of just gl?`

I might get some time this weekend to try it out. I think I had some error last time i tried that I'll have to look into.

**Comment by carnage702** [comment]
> 
> 
> `can you compile a rice build with latest changes instead of just gl?`
> 
> I might get some time this weekend to try it out. I think I had some error last time i tried that I'll have to look into.

any luck with rice?

**Comment by carnage702** [comment]
> 
> 
> Where's 2 happening, in WiiVC mode? I'll take a look at compiling a release if I find some free time this week.

so any chance for that compile? its been over a month i would really like rice with cpu clock divider

**Comment by emukidid** [comment]
Try these, compiled with:

> devkitPPC release 36 8.4.0
> libOGC 1.8.24-1

[wii64-master.zip](https://github.com/emukidid/Wii64/files/5472234/wii64-master.zip)

**Comment by carnage702** [comment]
> 
> 
> Try these, compiled with:
> 
> > devkitPPC release 36 8.4.0
> > libOGC 1.8.24-1
> 
> Link time optimisation doesn't seem to work in this dkPPC release with wii64 so it might be slower than expected.
> 
> [wii64-master.zip](https://github.com/emukidid/Wii64/files/5472234/wii64-master.zip)

so far i tryed the wiivc dols on wiivc and everytime i try changing the game or even the cpu clock i just get a dsi exception afew seconds after the game restarts,, seems it only runs well the first time you boot a game, any game booted after or restarted by changing cou clock divider just get dsi exception
![thumbnail_IMG_20201102_071602](https://user-images.githubusercontent.com/12446178/97840274-a2d1b500-1cdb-11eb-96e0-bd24f7afb907.jpg)

any reason why the dols are separated btw? since on fix94 1.2 recompile the dols work on regular wii and wiivc at the same time tough.

**Comment by carnage702** [comment]
after further testing the constant dsi exceptions only happen on rice vc dol, im guessing there is a memory leak somewhere? gl vc seems preety good altough you didnt port all not64 fixes for gl right? it seems something is missing for instance battlezone rise of the dogs, while it isnt perfect on not64 it shows abit more correct gfx than this gl build.

**Comment by emukidid** [comment]
Keep in mind that everything Rice is WIP, memory allocations aren't working properly so yeah it runs out of memory eventually, that needs to be fixed. I'll need to perform another merge from Not64 as well possibly to fix the remaining glN64 changes (if any).

**Comment by carnage702** [comment]
> 
> 
> Keep in mind that everything Rice is WIP, memory allocations aren't working properly so yeah it runs out of memory eventually, that needs to be fixed. I'll need to perform another merge from Not64 as well possibly to fix the remaining glN64 changes (if any).

i see but i never got any dsi exception from fix94 recompile of rice so i had no idea this was an issue, since i never got a dsi exception on the 1.2 version of rice.

but yeah everything seems to work as intended gamepad, cpu clock speeds and such besides the debug prints on screen and the dsi exceptions on rice both dols version seems good.

Also i noticed your missing some speed limiters on wii64 vs not64

south park rally runs normaly on not64 and yet it runs too fast on wii64 even this new dol, same for earthworm jim 3d boss battles, they run too fast on wii64 vs regular on not64, also noticed a racing game that also runned too fast vs not64 but i cant recall the name now.

**Comment by carnage702** [comment]
> 
> 
> Keep in mind that everything Rice is WIP, memory allocations aren't working properly so yeah it runs out of memory eventually, that needs to be fixed. I'll need to perform another merge from Not64 as well possibly to fix the remaining glN64 changes (if any).

just wondering what rice version did you port to wii64? 5.11? 6.12? a mix of many versions?

**Comment by emukidid** [comment]
It's super old, it's from mupen64 1.5 (before the 2.0 plugin API changes). I'm becoming more motivated to work on this lately (but finding free time gets more difficult :P) so hopefully I'll fix some of the issues.

**Comment by carnage702** [comment]
> 
> 
> It's super old, it's from mupen64 1.5 (before the 2.0 plugin API changes). I'm becoming more motivated to work on this lately (but finding free time gets more difficult :P) so hopefully I'll fix some of the issues.

nice to ear, maybe the lockdown of covid around the world gets you free time to work on finishing rice and do a release since its well deserving one :p 

btw did extremx no expoding polygon fix only applys to gl pluggin? can be putted on rice? im guessing they have dierent takes on the polygon explosion issue?

**Comment by carnage702** [comment]
So any progress on this recompile with cpu clock divider?

**Comment by emukidid** [comment]
Yes, I started to fix the bugs in Rice with the texture manager cache since it's pretty much unusable otherwise.

**Comment by carnage702** [comment]
> Yes, I started to fix the bugs in Rice with the texture manager cache since it's pretty much unusable otherwise.

Nice, don't know if it's of any use to you but fix94 did make a stable rice compile on his fork from way back, not sure if he removed features or not but played entire games without dsi exceptions.

**Comment by emukidid** [comment]
He limited available memory to the dynarec, I'd rather avoid that and just fix the texture cache to be used properly.

**Comment by emukidid** [comment]
Made some good progress yesterday on this, I'll prepare builds soon, just want to fix a few more things with it.

**Comment by carnage702** [comment]
> 
> 
> Made some good progress yesterday on this, I'll prepare builds soon, just want to fix a few more things with it.

cant wait xD also does the extrems not64 no exploding polygons fix can be applyed to rice or its for gl64 only fix? some games do have some stretched vertexes on rice.

**Comment by emukidid** [comment]
[wii64-master.zip](https://github.com/emukidid/Wii64/files/5564478/wii64-master.zip)
Try this version when you get a chance. Should fix debug appearing and also fix crashes with Rice.

**Comment by carnage702** [comment]
> 
> 
> [wii64-master.zip](https://github.com/emukidid/Wii64/files/5564478/wii64-master.zip)
> Try this version when you get a chance. Should fix debug appearing and also fix crashes with Rice.

just tested it for afew hours the wii vc version of the dols and everything seems fine both rice and gl64, looks like a great release.

btw just asking will this rice have fb textures? or its something that is incompatible with it?

**Comment by carnage702** [comment]
any chance we can get this version out before christmas so everyone can have it? xD

**Comment by niuus** [comment]
> [wii64-master.zip](https://github.com/emukidid/Wii64/files/5564478/wii64-master.zip)
> Try this version when you get a chance. Should fix debug appearing and also fix crashes with Rice.

After months having it in the hard drive, only today i was able to test this.

The only weird things that i've found, is that the sound tends to crackle a bit, the Dpad-right on the physical controller seems to be tied at the same time to C-button-down pressing (on the Wii U Pro Controller), and the 240p option does not seem to be working now (used VideoMode from 1 to 3).

Thanks for your work!

**Comment by carnage702** [comment]
> 
> 
> [wii64-master.zip](https://github.com/emukidid/Wii64/files/5564478/wii64-master.zip)
> Try this version when you get a chance. Should fix debug appearing and also fix crashes with Rice.

btw i just tested multiplayer with this today and with the gamepad is a no go~
using wiiu gamepad on wii64 menu it shows correct gamepad player one and wiiu pro player 2 but ingame the gamepad has no control over the game and the wiiu pro controller takes controll of both player 1 and 2 inputs so you can control both characters with wiiu pro lol im guessing its a controller bug somewhere you forgot to had wiiu gamepad to the list of controllers ingame.

**Comment by emukidid** [comment]
> btw i just tested multiplayer with this today and with the gamepad is a no go~
> using wiiu gamepad on wii64 menu it shows correct gamepad player one and wiiu pro player 2 but ingame the gamepad has no control over the game and the wiiu pro controller takes controll of both player 1 and 2 inputs so you can control both characters with wiiu pro lol im guessing its a controller bug somewhere you forgot to had wiiu gamepad to the list of controllers ingame.

Seems likely, I'll test it out again once I've got the Wii U set up.

**Comment by carnage702** [comment]
> 
> 
> > btw i just tested multiplayer with this today and with the gamepad is a no go~
> > using wiiu gamepad on wii64 menu it shows correct gamepad player one and wiiu pro player 2 but ingame the gamepad has no control over the game and the wiiu pro controller takes controll of both player 1 and 2 inputs so you can control both characters with wiiu pro lol im guessing its a controller bug somewhere you forgot to had wiiu gamepad to the list of controllers ingame.
> 
> Seems likely, I'll test it out again once I've got the Wii U set up.

should be an easy fix since it seems to be some missing order in the multiplayer tab with gamepad.

**Comment by saulfabregwiivc** [comment]
Anyone can make a new version of Wii64 1.2 (both glN64 and Rice GFX) for include again @FIX94's fixes and also capability to use IOS 58 and use on Wiiflow as a plugin (with arguments support of course)? Greetings

**Comment by carnage702** [comment]
> 
> 
> > [wii64-master.zip](https://github.com/emukidid/Wii64/files/5564478/wii64-master.zip)
> > Try this version when you get a chance. Should fix debug appearing and also fix crashes with Rice.
> 
> btw i just tested multiplayer with this today and with the gamepad is a no go~
> using wiiu gamepad on wii64 menu it shows correct gamepad player one and wiiu pro player 2 but ingame the gamepad has no control over the game and the wiiu pro controller takes controll of both player 1 and 2 inputs so you can control both characters with wiiu pro lol im guessing its a controller bug somewhere you forgot to had wiiu gamepad to the list of controllers ingame.

emukid please dont forget to adjust wiiugamepad so it doesnt use the same slot one in multiplayer and plays nice with other controller slots.

**Comment by carnage702** [comment]
So emukid how close are we from the official release of wii64 1.3 to the public?  seems you added all extrems fixes to gl version already so it should be close no? unless you want to do more rice fixes before release?

**Comment by emukidid** [comment]
The last thing I was going to look at before a release was actually in your comment above and then a re-test of the "WiiVC" build to see if it even makes sense to call it that (cause you were having some speed too fast issues I recall). If the "WiiVC" release only makes sense as a GamePad supported release and if that works in vWii mode then I might need to rename/repurpose it.

**Comment by carnage702** [comment]
> The last thing I was going to look at before a release was actually in your comment above and then a re-test of the "WiiVC" build to see if it even makes sense to call it that (cause you were having some speed too fast issues I recall). If the "WiiVC" release only makes sense as a GamePad supported release and if that works in vWii mode then I might need to rename/repurpose it.

Afaik you only need one version since every vwii app works just fine in wiivc with wiiu gamepad support, nintendont, any Wii emulator with wiiu gamepad support really.

**Comment by carnage702** [comment]
> 
> 
> The last thing I was going to look at before a release was actually in your comment above and then a re-test of the "WiiVC" build to see if it even makes sense to call it that (cause you were having some speed too fast issues I recall). If the "WiiVC" release only makes sense as a GamePad supported release and if that works in vWii mode then I might need to rename/repurpose it.

if you need anything tested out on wiiu with the single version and wiiu gamepad let me know im happy to test.

**Comment by carnage702** [comment]
> It's fine, I just need to sit at my PC and test this all out, everything is still set up thankfully.
Did you took a look at the wiiu gamepad order in multiplayer? So it doesn't share slot 1 with wiiu pro and friends?

**Comment by saulfabregwiivc** [comment]
Hi there @emukidid, since i see that commits updates are now a bit stuck, can you compile all builds with all commits of Wii64? For my testing purposes plz...

I know Wii64 1.3 isn't still coming but i want to test how's the progress of the Wii64 comparing to Wii64 1.2.

**Comment by emukidid** [comment]
Closing this one. Please create separate issues on the tracker for anything remaining.
