### ISSUE TITLE
Issues with Wii64 (Rice)

### ISSUE THREAD

**Issue by X4X5** [emukidid/Wii64#34]
I started using the Wii64 (Rice) Homebrew app, and found the RiceVideo.cfg file. I found an option there called "LoadHiResTextures", because when I tried loading textures for Paper Mario, they wouldn't load. So I enabled that, went to the app again, but as soon as Paper Mario loaded, the emulator crashed with a bunch of visual code on the screen. Can someone explain to me how texture packs on Wii64 work? Because it's not very clear on what to do

**Comment by emukidid** [comment]
You need to use the Texture Packer from the releases section ([Hi-Res Texture Packer (java) v1.2](https://github.com/emukidid/Wii64/releases/tag/texturepacker_1.2)) and it will make a texture pak for a single game that then needs to go on your SD card at SD: /wii64/hires/texture.pak.

You then also need to use the hi-res enabled build of Wii64 from ([here](https://github.com/emukidid/Wii64/releases/tag/HiResTest)). It's all very experimental so don't expect everything to work.

**Comment by X4X5** [comment]
Do I need to use a USB loader like Wiiflow?
