### ISSUE TITLE
Lock Vi/s maximum limit in general

### ISSUE THREAD

**Issue by carnage702** [emukidid/Wii64#37]
Losts of games hang around 61,63 vis and same with fps abit over abit lower than maximum, unlike not64 wich has a cap.

NTSC games should have VI/s max value locked at 60 Vi/s
Pal games should have a lock of 50 VI/s 
the way it is just makes games abit choppy because they can go abit over a maximum value lock would be perfect for overall good solid experience on any games that run at full speed at all times.

**Comment by emukidid** [comment]
They should be, what platform are you using? If it's WiiVC, that's untested essentially at this point since I've packed my Wii U up for now.

**Comment by carnage702** [comment]
> 
> 
> They should be, what platform are you using? If it's WiiVC, that's untested essentially at this point since I've packed my Wii U up for now.

well they arent top capped per say for instance i saw many games running at 61 and such VI/s so its capped but not at 60.0 like they should be i guess, i always tested in vwiiVC for instance  duck dogers runs at 62.83 or something of the likes instead of 60.0 and afew more games i noticed.

**Comment by carnage702** [comment]
so maybe its some bad calculation for games to not pass 60.0? i remenber extrems saying vwii runned like afew mhz slower than the regular wii or something.

**Comment by Extrems** [comment]
Wii U, not Wii.

**Comment by carnage702** [comment]
> 
> 
> Wii U, not Wii.

i did say vwii which is in wiiu xD and im guessing there is some miscalculation since im suposiing wiivc runs at the same exact speed as the vwii and that is why games run between 62-67 vi/s in wiivc inject.

but my memory is correct right? vwii does run afew mhz slower right?

**Comment by emukidid** [comment]
I'm still very confused.

vWii = Virtual Wii on Wii U.
WiiVC Inject = Wii U CPU speed, pseudo Wii mode on Wii U.

Which one are you using?

**Comment by Extrems** [comment]
WiiVC runs slightly slower than normal Wii U.

**Comment by carnage702** [comment]
> I'm still very confused.
> 
> vWii = Virtual Wii on Wii U.
> WiiVC Inject = Wii U CPU speed, pseudo Wii mode on Wii U.
> 
> Which one are you using?

I use Wii c inject but I don't overclock it to Wii u speed if I don't wanna play a intensive game, since most games run fine at regular speed.  Default Wiivc inject cou speed is the same speed as vwii.

**Comment by Extrems** [comment]
It's neither an overclock nor Wii U speed.

**Comment by carnage702** [comment]
> It's neither an overclock nor Wii U speed.

I know it's like 1,21 or something, fun fact fix said he could overclock even past wiiu speed but he was afraid the cpu overheated, I think he reached like 1,30 something and could do more with his code if he wanted.


Basically you got 
Wii,vwii,Wiivc inject which all should run at 729 I think but Wiivc inject can be run at close to wiiu speed of 1,21 or something

**Comment by carnage702** [comment]
> 
> 
> I'm still very confused.
> 
> vWii = Virtual Wii on Wii U.
> WiiVC Inject = Wii U CPU speed, pseudo Wii mode on Wii U.
> 
> Which one are you using?

i did some further testing but now im more confused i tryed all options

i tryed original wii,vwii and wiivc.

So you got 4 dols on your master folder
wii64gln64.dol
wii64rice.dol
wii64gln64-wiivc.dol
wii64rice-wiivc.dol

so far i only tested the wiivc dols but todays i decided to test the dols that dont have wiivc in the name and both of those are broken without speed limiters, what are they for? gc? becuase both of those dols without wiivc in the anme just run amok here is a picture on the original wii and its the same on vwii and wiivc too so no idea what they are for unless if they are for the GC?
![wii](https://user-images.githubusercontent.com/12446178/100026231-4ea18880-2de2-11eb-95e7-c76f25c7d7ba.jpg)


So leaving those 2 dols without wiivc in the name alone that have no speed limits lets talk about not64, this is not64 running mario kart on wii,vwii or wiivc all the same see the VI/s its rock solid
![not64](https://user-images.githubusercontent.com/12446178/100026343-8d374300-2de2-11eb-8421-951be29defd7.jpg)

now the wiivc dols actualy work and have the same limitr on wii,vwii and wiivc since they all run with the same wierd limiters that dont stay still and go over 60 constantly
both gl and rice is the same lock speed on mario kart 64 they opscilate between 61-63 constantly.
![61](https://user-images.githubusercontent.com/12446178/100026526-e0a99100-2de2-11eb-86ae-a169e8ecc4b4.jpg)

![62](https://user-images.githubusercontent.com/12446178/100026543-e7d09f00-2de2-11eb-94ec-2393b165d900.jpg)

So what i mean is you need to lock them to 60.0 and stay there and same for pal on 50, for isntace some games go as far as 62-65 constantly.

**Comment by carnage702** [comment]
i found out you need to manually edit the settings.cfg to get the fps lock working, if you go to your settings file and choose limit vi to 1 it will stay like not64 locked 60 and 30fps for example. not sure why its isnt 1 by default?
