### ISSUE TITLE
Port some "fixes" from mupen64-360?

### ISSUE THREAD

**Issue by carnage702** [emukidid/Wii64#38]
So i finally got a jtag xbox360 and found mupen64-360 and the credits do say its a port of wii64 with rice so im guessing due to similar architeture and being the same program it should be easy to port the diferences?

while wii64 compatibility is vastly superior i noticed some games that work on mupen64-360 that dont work on wii64 not sure if their rice pluggin is diferent or if they did some dynarec changes but if these changes to be ported to regular wii64 it would be preety great imo

1-**rat attack** boots and plays seemingly perfect on mupen64-360 while on wii64 it just crashes on both cores and video pluggins
2-**disney tarzan** on mupen64-360it boots and plays just fine but has no sound maybe they missed something, like the abode game on wii64 we get nothing.
5-**hydro thunder** starts fine but has no sound and crashes in the mid of the races but hey still better than the black screen of wii64
4-**Gex 64 enter the gecko** runs and starts just fine, on wii64 you need to start it onintrepreter and then do a save state or switch to dynarec to get it going at regular speed it wont start in dynarec.
5-**paperboy 64** same as abode starts and runs fine, on wii64 we have to use intrepreter and then do save states and change to dynarec

while i only noticed this it would be 5 good fixes for compatibility sake which should be easy to be ported back since its a port of wii64 to begin with right?

**Comment by Extrems** [comment]
We already got what we could from it.

**Comment by carnage702** [comment]
> 
> 
> We already got what we could from it.

but you guys took the fixes from when you were only using gl64 right? maybe now that emukid is officially using rice plugin this fixes for this games are dependent on rice itsef and dont work on gl64?

**Comment by carnage702** [comment]
> 
> 
> We already got what we could from it.

extrems i found an interesting thing lol, i was messing around with not64 and if you use wiiu overclock and cpu clock divider set to 1 disney tarzan actualy boots but after some time it will freezes with screeching noise, is this some cpu error codding or whatver? i tested it 3 times without wiiu overclock the game does not boot, maybe those games booted on xbox360 because the cpu clock was higher? 

just found this interesting not sure if you do too, if you want to test it check for yourself.

**Comment by emukidid** [comment]
mupen64-360 kind of took its own approach to things, I'm sure you've seen the dynarec mode options. It's easier to focus and try to fix the issues directly in wii64/not64 at this point rather than looking at what mupen64-360 did and what from those changes happened to fix things.

**Comment by carnage702** [comment]
> 
> 
> mupen64-360 kind of took its own approach to things, I'm sure you've seen the dynarec mode options. It's easier to focus and try to fix the issues directly in wii64/not64 at this point rather than looking at what mupen64-360 did and what from those changes happened to fix things.

i understand, but what about tarzan game, even on wii64 the one you compiled with cpu clock divider the game boots if you pick  cpu clock 1 with overclock or not, sure it still freezes further on after a set ammount of time but it should probably give a light to an issue that might affect more games? and on rice tarzan plays perfectly, if it didnt freeze it would be a completely perfect game xD

**Comment by saulfabregwiivc** [comment]
Wii64 and Not64 must have also code from mupen64-360.

@FIX94 have done that with Mupen64GC-FIX94 r2 (https://github.com/FIX94/mupen64gc-fix94) and in the revision r2 has these changes:
> -copied over code from mupen64-360 and not64 so blast corps and donkey kong 64 boot up
> -added pause hack for zelda ocarina of time so it pauses quickly now
> -stretched out displayed image to fill screen better on wiiu gamepad
> -better exit code so it now should not crash anymore if not booted from HBC

Anyone iof you are interesting in doing that for improve Wii64/Not64?

**Comment by Extrems** [comment]
We already did when mupen64-360 was being worked on.

**Comment by carnage702** [comment]
> 
> 
> We already did when mupen64-360 was being worked on.

the only thing missing from fix94 r2 is that wetrix does work ingame on fix94 r2 release while on wii64/not64 all we get is some messed up background covering everything, not sure what part he changed to get that fixed.

**Comment by saulfabregwiivc** [comment]
> > We already did when mupen64-360 was being worked on.
> 
> the only thing missing from fix94 r2 is that **Wetrix** does work ingame on fix94 r2 release while on wii64/not64 all we get is some messed up background covering everything, not sure what part he changed to get that fixed.

don't forget that **Mortal Kombat 4** also got fixed on mupen64gc-fix94 r2 that the HUD (health meter) doesn't disappear at the start on each round, thing that happens on regular Wii64/Not64

**Comment by carnage702** [comment]
> We haven't forgotten anything. It only works by happenstance with its incomplete solution to the depth range problem.

maybe that is a hint to further improve the depth range problem i know there is still some depth range problems  besides wetrix/mortal kombat4 health bars disapearing behind backgrounds  also on games like quake,duke nukem,earthworm jim,glover where the collectibles/enemys appear in front of 3d objects, im guessing no one got a perfect depth range solution yet for the wii, hopefully one day it will come true.

**Comment by Extrems** [comment]
There is no hint. It's a dead end.

**Comment by carnage702** [comment]
> There is no hint. It's a dead end.

well it was worth a shot.
