### ISSUE TITLE
Mirror mode issues

### ISSUE THREAD

**Issue by carnage702** [emukidid/Wii64#39]
Some rancing games have mirror modes where the track is mirrored and you can usually access it after unlocking it i noticed both gl64 and rice both have this issue

when playing mirror modes in games like diddy king racing adventure 2 or destruction derby 64 professional(tracks are mirrored) the graphics just become inside out and the controls become reversed, i haven't tested all racing games with mirror modes but this seem it will affect more games, is it something wii64 is ignoring on reversing the gfx coordinates and inverting the controls? seems it should be an easy fix where one just has to find the inverse mechanism to trigger somewhere.

**Comment by carnage702** [comment]
This was fixed on the latest not64 release by extrems hopefully uou can port it over before wii64 1.3 its released xD

Also emukid i saw on your cmd that wiivc default cpu clock divider is 1, and i beg you let it be 2 like on the wii since most games dont need overclock so people dont always start wii64 with overclock so no need for 1 to be default imo.

**Comment by emukidid** [comment]
Count Per Op will be 2 as of a173ab459fd7b6e4b98b1f14f58b4dc0f0753587 for WiiVC too by default.
Mirror mode is fixed in glN64 here d01855a2279a861fa8490c376668b34d257f59be.
I'll look at trying to fix it in Rice eventually, but I'll raise a separate issue for it.
