### ISSUE TITLE
Missing Fix94 fixes from 1.2 compilation for Rice?

### ISSUE THREAD

**Issue by carnage702** [emukidid/Wii64#41]
So i was just messing with fix94 1.2 latest rice compilation and noticed a huge diference

on **beetle adventure racing**  for instance **fix94 1.2 recompile of rice** has correct sky texture and all the trees and bushes and their correct format while on the latest wii64 rice compile by wii64 even with the fixes from upfront the sky is broken and the trees are all messed up, any chance you can maybe look at his code and see if he fixed some more codding on rice that actualy made huge diferences?

**Comment by emukidid** [comment]
It's true FIX94 did have a stab at fixing some of the geometry issues however it's uncertain how much else broke as a result. A detailed comparison of the changes would be required in order to make more sense of the differences.

**Comment by carnage702** [comment]
> It's true FIX94 did have a stab at fixing some of the geometry issues however it's uncertain how much else broke as a result. A detailed comparison of the changes would be required in order to make more sense of the differences.
I basically did test th entire n64 collection with fix94  commit and I didn't saw any broken geometry that isn't on your build tbh, if you want you can compile a version with fix94 geometry plus your fixes and I will do a general test

**Comment by carnage702** [comment]
any update on this? like i said i wouldnt mind doing the testing myself if needed.

**Comment by saulfabregwiivc** [comment]
anyone is interested in this of adding again @FIX94's fixes, improvements and features to the 2020/2021 version of Wii64 1.2 Rice?

**Comment by emukidid** [comment]
Can you point me to the commits you think these changes reside in? I can only see his glN64 changes which should already be in Wii64 now (via Not64 merges).

**Comment by saulfabregwiivc** [comment]
but @FIX94 made his mod for both glide (glN64) GFX and Rice GFX versions of Wii64 1.2, plus so many options such use NAND as virtual RAM and autoboot (autostart) a game ROM when launching from HBC.
@emukidid, can you and anyone can fix them in 1.2 r19-11-2020 and release a new version with all those fixes?

**Comment by carnage702** [comment]
> 
> 
> Can you point me to the commits you think these changes reside in? I can only see his glN64 changes which should already be in Wii64 now (via Not64 merges).

im guessing you need to remember the rice version you gave him and check for differences? you or extrems? not sure who handed rice to fix94?

btw i did afew more texts and fix94 did fix some broken textures on rice

latest rice version you gave us to test here on github

Beetle adventure racing
broken sky and trees and bushes all over
![IMG_20210808_163941](https://user-images.githubusercontent.com/12446178/128637680-01802822-ea92-4fe0-a5d1-319fddf67f85.jpg)

Yoshi story
broken everything
![IMG_20210808_164039](https://user-images.githubusercontent.com/12446178/128637683-604ad501-caca-4ad4-8b29-3643139a5772.jpg)

Fix94 recompile of 1.2
beetle adventure racing fixed sky and trees and bushes basically almost perfect gfx.
![IMG_20210808_163704](https://user-images.githubusercontent.com/12446178/128637711-74106ebe-fed0-4352-8ee0-2e18292655f0.jpg)

yoshi story you can now actually see the levels and some things, still cant correctly see eggs or enemies but its a huge step up from what we have now
![IMG_20210808_163757](https://user-images.githubusercontent.com/12446178/128637723-0e3dd63c-36b4-440c-8342-1a777471e7d5.jpg)


this is just 2 examples, and im guessing there are alot more i havent compared the 2 by much but its preety significant changes to textures imo.

emukid if you can find the rice version fix was handled and compare to his 1.2 recompile you can maybe see the differences?

**Comment by emukidid** [comment]
Can you link me to the Rice version, cause it's broken with this version: https://github.com/FIX94/Wii64/releases/tag/20171121

**Comment by carnage702** [comment]
> 
> 
> Can you link me to the Rice version, cause it's broken with this version: https://github.com/FIX94/Wii64/releases/tag/20171121

see my isssue here i think i found out the problem, i also use that link of rice and it works for me
https://github.com/emukidid/Wii64/issues/49

i think it has to do with settings being 3 and 4 or just actual default values that are not on the cfg file.

**Comment by carnage702** [comment]
the only fix that fix94 made that doesnt work on wii64 and not64 is wetrix

wetrix has some texture issues but works and plays fine while ingame while on not64/wii64 you cant see the map while playing only works on this version of fix94 wii64
https://github.com/FIX94/mupen64gc-fix94/releases/tag/r2   not sure if you want to take a look at what he made for wetrix to work ingame.

**Comment by emukidid** [comment]
> the only fix that fix94 made that doesnt work on wii64 and not64 is wetrix
> 
> wetrix has some texture issues but works and plays fine while ingame while on not64/wii64 you cant see the map while playing only works on this version of fix94 wii64
> https://github.com/FIX94/mupen64gc-fix94/releases/tag/r2 not sure if you want to take a look at what he made for wetrix to work ingame.

Can you split this one off into a separate issue? I'd like to close this one as the core issue was fixed in 15ca7353dd3e76d74bd6d07253de9ccaf16d5d08 which was causing the ini to fail to apply to the proper game.

**Comment by carnage702** [comment]
> 
> 
> > the only fix that fix94 made that doesnt work on wii64 and not64 is wetrix
> > wetrix has some texture issues but works and plays fine while ingame while on not64/wii64 you cant see the map while playing only works on this version of fix94 wii64
> > https://github.com/FIX94/mupen64gc-fix94/releases/tag/r2 not sure if you want to take a look at what he made for wetrix to work ingame.
> 
> Can you split this one off into a separate issue? I'd like to close this one as the core issue was fixed in [15ca735](https://github.com/emukidid/Wii64/commit/15ca7353dd3e76d74bd6d07253de9ccaf16d5d08) which was causing the ini to fail to apply to the proper game.

sure no problem.
