### ISSUE TITLE
Wii64 Rice video freezes, audio plays

### ISSUE THREAD

**Issue by zpaoktts** [emukidid/Wii64#43]
I've downloaded Wii64 Rice version from Fix94 unto my USB. When I load a ROM (007 Goldeneye for example) and hit Play, the screen freezes but the audio continues. I've unzipped the ROM files as suggested on the wiibrew discussion board but no luck. Not sure what to do. Not64 and the gln version work perfectly fine. I'm new to softmodding so any help is appreciated.

**Comment by emukidid** [comment]
Try the latest version from this issue thread instead: https://github.com/emukidid/Wii64/issues/28

I need to muster up enough time to make a proper release sometime soon.

**Comment by zpaoktts** [comment]
You've done so much already from what I can see! So with this, essentially I replace the boot.dol with the Rice.dol and glN64.dol? or do I retain the boot.dol and simply add these extras into the original folders?

**Comment by emukidid** [comment]
You'd need to replace your boot.dol with one of those and name it boot.dol. Keep the original around, or duplicate the entire apps/wii64 dir to have multiple (just edit the .xml in a text editor to make them unique).

**Comment by zpaoktts** [comment]
I'll give it a shot and let you know how it goes. Thanks a ton!

**Comment by zpaoktts** [comment]
Update: the ROMs now load but run at a really fast speed.

**Comment by zpaoktts** [comment]
Update: I used the wii64-Rice-wiivc.dol file instead and it seems to be working great!

**Comment by carnage702** [comment]
> 
> 
> Update: I used the wii64-Rice-wiivc.dol file instead and it seems to be working great!

yeah you need to use both wiivc dols for rice and gl or else you got no speed limiters.
