### ISSUE TITLE
Wii64 new official release

### ISSUE THREAD

**Issue by Kappa971** [emukidid/Wii64#44]
Hi, I noticed there have been several fixes but the latest version of Wii64 is 1.1 which is several years old. A new release would be useful. Thanks for this emulator :)

**Comment by emukidid** [comment]
I'm keen to do a new release shortly, just want to fix a couple of things and test it on all platforms somewhat before sending it out.

**Comment by Kappa971** [comment]
Nice, thanks :)

**Comment by carnage702** [comment]
> I'm keen to do a new release shortly, just want to fix a couple of things and test it on all platforms somewhat before sending it out.

If you want a wiiu tester let me know xD

**Comment by saulfabregwiivc** [comment]
don't forget all the fixes, improvements and features that @FIX94 did in his build of Wii64 (http://github.com/FIX94/Wii64) :)

**Comment by carnage702** [comment]
i wish emukid did the release before Christmas too, sadly it doesnt seem like it will happen this year, maybe next year.

**Comment by saulfabregwiivc** [comment]
> i wish emukid did the release before Christmas too, sadly it doesnt seem like it will happen this year, maybe next year.

me too @carnage702!

I can't wait...
I want also my pull request for add compatibility for WiiFlow to Wii64 so we can enjoy in WiiFlow but also for game channel forwarders on Wii Menu... :)

Hope @emukidid can compile a new version of Wii64 with my pull request and the latest commits before Christmas :)

**Comment by saulfabregwiivc** [comment]
@Kappa971 Wii64 1.3 was released.
But still there are two few issues: incorrect RiceVideoLinux.ini codification and Wiiflow compatibility missing.
I've opened two issues (i've also included the ini file for fix that bug) and a pull request for add compatibility for Wiiflow.

@emukidid will close it ;)
