### ISSUE TITLE
Option to always use the "Advanced" view like Not64?

### ISSUE THREAD

**Issue by NintendoManiac64** [emukidid/Wii64#46]
I much prefer the behavior in Not64 where, if you exit a game to go back to the emulator menu, it's the same screen as Wii64's "advanced" menu.  The main benefit is that, if you were already running a game, then it will default to highlighting "Resume Game" which makes it very easy to, well, resume the game (you just press the A button).

On Wii64 by comparison, it's all too easy to accidentally reset or load a different game because, even when a game was running, it defaults to highlighting "New Game".

(as for why I don't just use Not64, it's because Bust-A-Move 2 has game-breaking graphical errors that requires using the Rice GFX version of Wii64.  The game might work on WiiSX RX, but that emulator lacks CDDA and therefore the game has no music)

Speaking of WiiSX RX, if this function *does* get implemented, then it may be prudent to make sure it also doesn't replicate a specific discrepancy in behavior exhibited by WiiSX RX v2.5 whereby, if you use autoboot and then return to the emulator menu, WiiSX RX will be highlighting "Load ISO" by default; this is a discrepancy because, if you load a game in WiiSX RX when **_not_** using autoboot, run the game, and then return to the emulator menu, WiiSX RX be highlighting "Resume Game" by default instead (which is the behavior I would think makes more sense).

**Comment by emukidid** [comment]
You can use this in the meta.xml to go straight to the Advanced view:
`   <arguments>`
`    <arg>MiniMenu=0</arg>`
`   </arguments>`

**Comment by NintendoManiac64** [comment]
> You can use this in the meta.xml to go straight to the Advanced view:

Perhaps then this function should be documented?

**Comment by emukidid** [comment]
Updated readme to document this in 61697d340838d3bd00b35873fe1dc966414a914c
