### ISSUE TITLE
"Home" button isn't an option for returning to emulator menu when using nunchuck or wii remote by itself despite being an option for classic controllers

### ISSUE THREAD

**Issue by NintendoManiac64** [emukidid/Wii64#48]
It would seem that, when using a nunchuck or when using a wii remote by itself, you can't set the "Home" button as the method for returning to the emulator menu when a game is running.

Yet for a classic controller, the "Home" button *is* an option for going back to the emulator menu, so perhaps this was simply an oversight?

　

For reference, Not64 allows one to use the "Home" button to return to the emulator menu when using a nunchuck or a wii remote by itself.

**Comment by emukidid** [comment]
Fixed in c92b03a94a9aedcea17d40cff9178eddd4e2efaa
