### ISSUE TITLE
Have a version using GLN64 like Not64?

### ISSUE THREAD

**Issue by NintendoManiac64** [emukidid/Wii64#50]
If there really will be a new build incorporating Fix94's various improvements and the like, then ideally there should be a GLN64 version as well as a Rice video version since some games (e.g. BattleTanx: Global Assault) have some graphical issues with text on Rice video while other games (e.g. Bust-A-Move 2: Arcade Edition) have minor albeit game-breaking graphical issues with the "shooter" on GLN64.

**Comment by emukidid** [comment]
There definitely will be a glN64 version as well as a Rice version in all future releases.
