### ISSUE TITLE
Increase deadzone for CC controllers?

### ISSUE THREAD

**Issue by NintendoManiac64** [emukidid/Wii64#51]
On my classic controller pro, BattleTanx: Global Assault (EUR) reads a slight input from the left analog stick even when the analog stick is in the default position no matter what I do.  GameCube controllers don't seem to have this issue, but seem to have their own issue where the analog sensitivity is a bit higher than the classic controller (though I haven't yet checked which one is more accurate compared to a real N64), albeit no where near the sensitivity on Not64 (which has the GameCube analog stick be much too sensitive).

For reference, Not64 and Fix94's Wii64 do not have this issue.

This was tested with the (only?) release build from 2018-02-16.

(it's also my impression that Not64 implements what raphnet calls ["high resolution mode" for classic controllers](https://www.raphnet-tech.com/support/classic_controller_high_res/) - I don't suppose that makes a difference, like maybe Not64 and Fix94's Wii64 are using the high-res controller mode while your version isn't?)

**Comment by emukidid** [comment]
The deadzone issue will be fixed in the next release. 8332e34b20f6316694e4d3c25213aae4ffef64e9 fixed it.

As for things like high resolution mode on controllers, niche features like that I feel like you'll have to use Not64 for, because otherwise what's the point of 2 separators emulators :D

**Comment by NintendoManiac64** [comment]
> As for things like high resolution mode on controllers, niche features like that I feel like you'll have to use Not64 for, because otherwise what's the point of 2 separators emulators :D

I'm not so sure what's so "niche" about it when it's supported by every single 1st party classic controller made...

As for Not64, it seems to no longer get updates and has the "skipmenu" autoboot issue where classic controllers don't operate properly.

**Comment by Extrems** [comment]
Bro, I put out an update just yesterday.

**Comment by NintendoManiac64** [comment]
> Bro, I put out an update just yesterday.

Forgive me for not checking when, for the last 14 months, there's been no update, and the version before that was put out only 4 days earlier before that 2020-06-09 version which looked to me like all of the signs of something that was no longer getting updates.

**Comment by NintendoManiac64** [comment]
> As for things like high resolution mode on controllers, niche features like that I feel like you'll have to use Not64 for, because otherwise what's the point of 2 separators emulators :D

Here's a big reason - the ability to use gamecube controllers with analog sticks that are overly-sensitive without handicapping classic controller users with lower analog stick precision.

Basically as it stands, Not64 has high-res classic controller analog but overly-sensitive gamecube controller analog.

Wii64 has sane-sensitivity gamecube controller analog but with low-res classic controller analog.

Why must it only be one or the other and not both?

**Comment by Extrems** [comment]
It's weird, I find Classic Controllers are way too sensitive and GameCube Controllers are just fine...

**Comment by NintendoManiac64** [comment]
> It's weird, I find Classic Controllers are way too sensitive and GameCube Controllers are just fine...

lolwut.  I could understand if it was a perceptual issue of simply being used to the more sensitive or less sensitive configuration, but you're straight up saying that you're seeing the _opposite_ sensitivity? O_o

For reference, this occurs with both an original classic controller and a classic controller pro.

I almost kind of wonder if it's game-related.  As usual, my go-to use-case that I've been testing with is BattleTanx: Global Assault in deathmatch using the "Rino" tank (available as the default is you select "Dark Angels" as your army).  With a Classic Controller, the Rino can rotate 360 degrees in around 3 seconds with, with a GameCube controller, the Rino takes more like 2 seconds to rotate 360 degrees.

And on a real N64 with a 1st party controller, the Rino also takes around 3 seconds to rotate 360 degrees.
