### ISSUE TITLE
Option for outputting at 50Hz for PAL games?

### ISSUE THREAD

**Issue by NintendoManiac64** [emukidid/Wii64#56]
As mentioned in #55 only the EUR version of BattleTanx: Global Assault works.  Since I have a TV that is capable of displaying a 50Hz signal whether via HDMI or component, I was wondering if it'd be possible for a setting to output PAL games with a 50Hz video signal in a manner similar to what Nintendont is able to (optionally) do?

Just to clarify, the game speed in the EUR version of BattleTanx: Global Assault is correct as-is, I'm jut trying to get the video output to appear less juddery since Wii64 and Not64 currently apply 12:5 pulldown and telecine the 25fps to 60Hz resulting in inconsistent frame delivery.  If the video was output at 50Hz instead, then it would have perfectly consistent frame-delivery (assuming the game runs at constant 25fps of course) of simply displaying each frame for two refreshes in the same manner that 30fps games operate on 60Hz displays.

**Comment by carnage702** [comment]
cant you already do that by modifing the config manualy?

VideoMode

    0 = VIDEOMODE_AUTO (default)
    1 = VIDEOMODE_PAL60
    2 = VIDEOMODE_240P
    3 = VIDEOMODE_480P
    4 = VIDEOMODE_PAL
    5 = VIDEOMODE_288P
    6 = VIDEOMODE_576P

guessing 4 is 576i
...

**Comment by NintendoManiac64** [comment]
Well bloody nora, that's exactly what I was looking for!  And in Not64, it even works as a meta.xml argument!
