### ISSUE TITLE
Your newest 2020-11-01 Rice build has major graphical issues in Bust-A-Move 2 vs FIX94's Wii64-Rice

### ISSUE THREAD

**Issue by NintendoManiac64** [emukidid/Wii64#57]
If you compare the title screen demo in "Bust-A-Move 2: Arcade Edition" on your 2020-11-01 build of Wii64-Rice to FIX94's 2017-11-21 release of Wii64-Rice, you can see that there are major graphical issues in your version but not in FIX94's.  Of particular note is, on the actual game play field (whether in the demo or in-game), you can see that the "shooter pointer" is completely invisible in your 2020-11-01 build but is very much visible in FIX94's.

It may also be worth noting that the "shooter pointer" being invisible is exactly the same graphical issue that occurs with glN64 (which is the whole reason I wanted to use Rice in the first place for that game).

**Comment by carnage702** [comment]
This was because rice ini didn't apply the fixes , emu kid already fixed that, so all rice changed will be the same as fix94
