### ISSUE TITLE
Player order completely ignores wii remote and/or GC pad player number if controllers or attachments are different

### ISSUE THREAD

**Issue by NintendoManiac64** [emukidid/Wii64#63]
If the 1st player wii remote has no attachment connected, the 2nd player wii remote has a nunchuck connected, the 3rd player wii remote has a classic controller connected, and there's a gamecube controller plugged into the 4th controller port on the Wii console...

...the gamecube controller is made player 1, the classic controller + 3rd player wii remote is made player 2, the nunchuck + 2nd player wii remote is made player 3, and the 1st player wii remote by itself is made player 4.

So basically player order is primarily decided as gamecube > classic controller > nunchuck > wii remote by itself, and _then_ only if a controller or attachment is the same will it then go by controller player number.

Is that not all a bit... absurd?  Outside of Not64 and WiiSX/R/X (which all basically use the same emulator front-end as a foundation), I don't think there's any other Wii software, commercial or homebrew, that operates this way.  Is it not much more sensible to just follow the controller player-number as-is like in Nintendont, with the single exception of gamecube controllers taking priority over a wii remote of the same player number (e.g. if you have 2 wii remotes and a gamecube controller in the 2nd port, the wii remotes would be made 1st and 3rd players and the gc pad 2nd player), again in the same way that Nintendont operates?

　

(apologies for continuing to junk up the issue tracker, but for all I know this may in fact be a legitimate bug and/or oversight rather than an intentional feature; to help sort out the wheat from the chafe I've gone back and labeled the things that are clearly not bugs or the like with "[FEATURE]" to match an existing issue submission by a different user on the WiiSX RX issue tracker so as to easily identify the crap that can be safely ignored)

**Comment by emukidid** [comment]
I can't recall if this was intentional but based on the order that was assigned internally in the emulator it seems like it's prioritizing the most "complete" of the controllers first, e.g. GameCube, and Wiimote by itself as last.

**Comment by NintendoManiac64** [comment]
But a classic controller is more "complete" than a gamecube controller, in fact a classic controller has enough buttons to map ALL of the N64 buttons without needing to use the right analog stick (the gamecube controller has 3 fewer buttons including "Home").

**Comment by Extrems** [comment]
I'm pretty sure it was intentional given the logic dedicated to this. This is why manual controller assignment is offered though.

**Comment by emukidid** [comment]
I don't want to mess with what we have here (especially since manual controller assignment exists too), closing issue.
