### ISSUE TITLE
Add missing commit from Not64 v20210829 to Wii64

### ISSUE THREAD

**Issue by saulfabregwiivc** [emukidid/Wii64#67]
Great work with that @emukidid, but @extremscorner added in the last update of Not64 (v2021-08-29) this commit for fix some issues:
https://github.com/extremscorner/not64/commit/75c0d1ae9606482453260ec7f10cea0f081f638c

The fixed things are:
* Added Wii Remote +Control Pad as analog source.
* Added AutoLoadSave option.
* Fixed regression from [03b282c](https://github.com/extremscorner/not64/commit/03b282c2953407ec0fc566887f25e110b06bdc92) .

Hope this be added to Wii64 too.

Best regards, @saulfabregwiivc

**Comment by carnage702** [comment]
im preety sure emukid knows about this he didnt added it on github becuase he didint have the time yet lol.

**Comment by emukidid** [comment]
This done as of 7cc764e40a7346ee6c8ed95347af05ddcaea11a1

Individual features such as auto load save options etc can come in separately, I was more interested in bringing the change to fix the regression through.
