### ISSUE TITLE
Emulator not reading my SD Card or Usb Drive

### ISSUE THREAD

**Issue by MrJayBoy13** [emukidid/Wii64#68]
It will not read after me, reformating, unlocking the sd card, cleaning the slot, and trying different builds of wii64, but it still doesn't work. Is this my wii, or is this a well known problem?

**Comment by carnage702** [comment]
Just you lol. Take a picture of your sd card root and a picture inside the wii64 folder

**Comment by MrJayBoy13** [comment]
![Screenshot 2021-09-15 at 7 18 14 PM](https://user-images.githubusercontent.com/84677793/133529639-b0c59d20-9c38-42fd-9778-7f2efcf2e780.png)
![Screenshot 2021-09-15 at 7 18 09 PM](https://user-images.githubusercontent.com/84677793/133529641-afd8095b-6932-447b-8e67-49d2ba496056.png)
![Screenshot 2021-09-15 at 7 18 17 PM](https://user-images.githubusercontent.com/84677793/133529642-23fe309b-446c-4ffe-a4cb-0662f9aeca5d.png)

**Comment by emukidid** [comment]
You need extracted ROMs for Wii64, also RiceVideoLinux.ini doesn't need to be inside the roms directory.

**Comment by carnage702** [comment]
Like emukid Said you need to open the zip file and extract the actual ROM inside of it. Also ricevideoLinux.ini goes into  SD: Wii64 folder and not inside the roms folder
