### ISSUE TITLE
Your RiceVideoLinux.ini still causes issues comparing to FIX94's RiceVideoLinux.ini on Wii64 1.3

### ISSUE THREAD

**Issue by saulfabregwiivc** [emukidid/Wii64#74]
In the problematic games which require Rice to run (Beetle Adventure Racing, Yoshi's Story, Donkey Kong 64) there are still issues caused by your file RiceVideoLinux.ini, comparing to FIX94's RiceVideoLinux.ini file that applies correctly the settings for each game.

Comparing your RiceVideoLinux.ini of your last release (Wii64 1.3) with FIX94's one (http://github.com/FIX94/Wii64), i see that they have the same settings but they have different codification, resulting that FIX94's ini file gets detected but yours doesn't.

I will attach the RiceVideoLinux.ini file of FIX94 for fix those issues with Wii64 1.3.

Hope this get fixed, @saulfabregwiivc
[FIX94 Wii64 RiceVideoLinux.ini file.zip](https://github.com/emukidid/Wii64/files/7764227/FIX94.Wii64.RiceVideoLinux.ini.file.zip)

**Comment by carnage702** [comment]
comparing the inis in hex it seems there is  2 .. after the title id and the actual name on emukid ini while fix94 only has 1 . and then 2 .. between the settings but after title id it seems to only use one . and 2 .. between settings.

seems its a formating issue of sorts?

**Comment by saulfabregwiivc** [comment]
@carnage702 looks like a formating issue.

@emukidid needs to rerelease Wii64 1.3 with the fix of @FIX94's RiceVideoLinux.ini which has correct formating for Wii64, but also for add arguments support for autostart game ROMs (see https://github.com/emukidid/Wii64/pull/71)

**Comment by leodexe** [comment]
I want to add Excitebike 64, this one has issues rendering the tracks properly with the 1.3 ini which doesn't happen with the 1.2 ini. Only unfixed issue is original Excitebike doesn't show Temp Bar correctly so you're better playing it on the NES emulator.

**Comment by carnage702** [comment]
emukid you never fixed this, your ricevideolinux.ini is still broken on release making all other rice settings fix not being applied any chance you fix that?

**Comment by emukidid** [comment]
Yeah I can have a look, the file attached here is FIX94's latest?

**Comment by carnage702** [comment]
> Yeah I can have a look, the file attached here is FIX94's latest?

Saulfabre has a pull request here with the file here with some fixes, just take that one.

**Comment by emukidid** [comment]
Forgive my memory on this all, but the changes made in that PR don't reflect the ones in the opening comment here (DK64) or did we already address those?

**Comment by carnage702** [comment]
> Forgive my memory on this all, but the changes made in that PR don't reflect the ones in the opening comment here (DK64) or did we already address those?

Tbh I don't know about dk64 , but the problem with the release ini on the release page is that the ini code doesn't get applied to the games, instead it created a new entry for each game and didn't use the previous configuration made for the game already on the ini, an easy game to test is bettle adventure racing , if the ini is being applied both trees and sky texture is fixed if not they are broken.

**Comment by emukidid** [comment]
Rice config file should be fixed in 6188ae77d81089b5ad024ef9d46dcafac58587dd and it also has the changes from the one in this PR.
