### ISSUE TITLE
Not showing up on homebrew screen

### ISSUE THREAD

**Issue by Kingkoopa64** [emukidid/Wii64#81]
I have this folder in both my apps folder and the root of my SD card can anybody show me a quick tutorial

**Comment by saulfabregwiivc** [comment]
You need to launch it from the Homebrew Channel (HBC) on vWii mode, not from Homebrew Launcher (HBL) on Wii U Menu.

**Comment by Kingkoopa64** [comment]
> 

I'm using it on the Wii

**Comment by carnage702** [comment]
> > 
> 
> I'm using it on the Wii

then you didnt place the correct folder in apps

sd:apps/wii64/boot.dol

and then the other wii64 folder goes in root
sd:wii64

there are 2 wii64 folders they are diferent, one for apps and one for root of the sd card, im guessing you swapped them or something.

**Comment by Kingkoopa64** [comment]
I only got one folder with a bunch of other folders

**Comment by carnage702** [comment]
> I only got one folder with a bunch of other folders also no boot.dol file was included

take a picture of your apps folder and then inside wii64 folder

**Comment by Kingkoopa64** [comment]
![IMG_20220303_142137](https://user-images.githubusercontent.com/100751455/156637468-823681ad-2658-446a-a8a5-1b74e89da028.jpg)
![IMG_20220303_142117](https://user-images.githubusercontent.com/100751455/156637472-69821f6c-4cbf-4ef4-ac42-847c306138ab.jpg)
![IMG_20220303_142127](https://user-images.githubusercontent.com/100751455/156637474-0dbd8850-ff74-4b3c-a70e-e7420b9651da.jpg)
![IMG_20220303_142110](https://user-images.githubusercontent.com/100751455/156637476-6507c2da-9f1d-451d-951e-9b9d97ad8d9f.jpg)

**Comment by Kingkoopa64** [comment]
Those 4 folders were dragged from a subfolder and the Wii64 that appears to be a notepad was also dragged out from a subfolder and the USB thing is actually my SD card

**Comment by carnage702** [comment]
you download totally wrong files lol you download the github repository source code  lol and not the actual files 

delete all that


download the 7z file only , 7z is like a zip you need to extract what is inside, so download 7z program to your pc and then right click extract on the 7z file that is where you get the correct files

**Comment by carnage702** [comment]
its just easier to give you the files since i see you dont know anything about computer or wii in general just download this
https://www.mediafire.com/file/rqjv4p0y8e8lesw/SD+root.zip/file

1- right click on it and select  extract here
2-open sd root folder
3-slect all 3 folder and right click copy
4-open your usb device and on the first screen it opens  on (the root) just right click and choose paste, if it asks to overwrite something just click yes
