### ISSUE TITLE
Games emulating at far too many frames (over 100FPS)

### ISSUE THREAD

**Issue by postwar-toaster** [emukidid/Wii64#85]
I recently upgraded from an ancient version and I'm having an issue where nearly every game seems to be getting hundreds of frames per second to the point they are too fast to play in any meaningful way. Beetle Adventure Racing which formerly was too slow to play is working fine now, so that's something I guess. This happens on both the rice and gl versions. I'm using the Wii version, on a normal retail wii purchased at launch but had to have the drive replaced and it's launched through homebrew.

**Comment by carnage702** [comment]
Need to delete your old config file on the wii64 folder ,then save a new one, and then make sure you have limit vis set to 1 or 2 on the new file.

**Comment by postwar-toaster** [comment]
I actually figured that out myself right after I typed that I upgraded add realized that my install had files the distribution didn't, but thanks for the reply! Couldn't find this on Google anywhere.Get Outlook for Android
