### ISSUE TITLE
Why did you make such a horrible emulator,

### ISSUE THREAD

**Issue by juanroman74454811** [emukidid/Wii64#90]
Im switching to Not64 instead,
It goes like a BSOD a little bit then returns back to normal,
Please make a new emulator that has no graphical issues and no game issues,

**Comment by juanroman74454811** [comment]
God doesnt like this emulator.

**Comment by saulfabregwiivc** [comment]
Please STOP
Even when it has some issues, Wii64 is still good nowadays, also because it's the only one with Rice GFX for Wii.

**Comment by juanroman74454811** [comment]
> Please STOP Even when it has some issues, Wii64 is still good nowadays, also because it's the only one with Rice GFX for Wii.

Oh, hence the issues, There are some graphical glitches on Banjo Kazooie, like Banjo having no eyes and almost any texture being glitchy.
