### ISSUE TITLE
SD2SP2 Support

### ISSUE THREAD

**Issue by Captain5567** [emukidid/Wii64#91]
I tried to use cube64 on my GameCube, but it won't look for the roms in the right directory. I don't know if its because it expects an sd card in the memory card slot, but it will not look for the roms in the right place. Any help?

**Comment by boldandbrad** [comment]
I appear to be having the same issue. I'm using SD2SP2 and Cube64 looks for roms at `sd:/wii64/roms`, but the sd card is actually mounted at `sdc:/...`

**Comment by Extrems** [comment]
Device names are application specific, but the default for the SD2SP2 with libfat *is* `sd:/`. However, Wii64 uses custom mount handling and shoves all SD cards under `sd:/`.

The SD2SP2 is currently only supported with Not64.

**Comment by saulfabregwiivc** [comment]
Likely added as of https://github.com/emukidid/Wii64/commit/1e05d75fe75ff7ad2057e7808892ba455df536f9

**Comment by Culkerz** [comment]
With this being pushed, can we get this recompiled and published as a release? This is awesome news for many expansion pak enjoyers
